[phases.setup]
nixPkgs = [
    "python39",
    "python39Packages.pip",
    "python39Packages.virtualenv",
    "postgresql_14",
    "gcc",
    "zlib",
    "zlib.dev",
    "libffi",
    "openssl",
    "pkg-config"
]

[phases.install]
cmds = [
    "chmod +x setup.sh && ./setup.sh"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn config.wsgi:application --log-file -"

[build.environment]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app:$PYTHONPATH"

[build.args]
PYTHON_VERSION = "3.9"
